#<NO_OVERWRITE> Remove this line for overwrite this file
#=======================================================================================================================
# CyborgAI
# CC BY-NC-ND 4.0 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
# Package: ai
#=======================================================================================================================
["DEVELOPER"]
brain=""" """
api= ["terminal","github_mcp"]
#=======================================================================================================================
["TRADING"]
brain=""" """
api= ["trade"]
#=======================================================================================================================
["WRITER"]
brain=""" """
#=======================================================================================================================
["DESIGNER"]
brain=""" """
#=======================================================================================================================
["DESKTOP"]
brain=""" """
#=======================================================================================================================
["VIDEO_EDITOR"]
brain=""" """
#=======================================================================================================================
["MUSIC_COMPOSER"]
brain=""" """
#=======================================================================================================================
["GAME_DESIGNER"]
brain=""" """
#=======================================================================================================================
["SECURITY_ANALYST"]
brain=""" """
#=======================================================================================================================
